# This file must be here for Renovate to understand that we use offline cache.

# Minimum viable config for Yarn to work. The rest is inherited from the root .yarnrc.yml file.
yarnPath: ../../.yarn/releases/yarn-3.0.1.cjs
